### ISSUE TITLE
Unable to extract entities job with non-default spacy model

### ISSUE THREAD

**Issue by laissezfarrell** [libratom/libratom#126]
After installing en_core_web_lg, I tried to extract entities using the following command:

`ratom entities -o ~/Desktop/export/entities_dupress-output-spacy-english-large.sqlite3 -pv -v --spacy-model en_core_web_lg  ~/Desktop/DUPress_email/`

During processing, I continue to run into the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 3xlwE

```

Extracting entities with the default spacy model still works, however.  I'm unsure if the error I experience is a ratom issue, an issue with my environment (BitCurator 2.0.16), or something else entirely.

**Comment by adetorcy** [comment]
Thanks for your feedback. I have not (yet) been able to reproduce your error but I have observed a much higher memory usage with `en_core_web_lg` than with `en_core_web_sm` for the same job.

Can you share your system specs for this run? RAM, CPU cores and swap memory in particular.

You might want to try processing a small subset of your email files and limiting the number of concurrent jobs (e.g. `-j 2` or `-j 1` if applicable), to see if it makes a difference.

**Comment by laissezfarrell** [comment]
Ah, that would make sense. I'm running the machine as a VM, with 

8+ gb ram
4 cores
2 gb swap
 given to it.

I'll try what you suggest in order to reduce the memory usage. I can also try on machines with more computing power.

thanks!

**Comment by adetorcy** [comment]
How did it go? Were you able to use `en_core_web_lg` successfully?
