### ISSUE TITLE
Windows issue still ongoing

### ISSUE THREAD

**Issue by Biedubbeljoe** [libratom/libratom#155]
Hi,

I saw that you closed my issue with "update dependencies", but all is up-to-date. Also used: pip install libratom -U
The next errors are logged while trying to process a pst file in Windows 10, after all is installed conform your site instructions:
----------------------
(base) C:\Users\user>ratom entities -p -vv -m C:\test\ratom.db C:\test\user@test.pst
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\ratom.exe\__main__.py", line 4, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\libratom\cli\cli.py", line 14, in <module>
    import libratom.cli.subcommands as subcommands
  File "c:\programdata\anaconda3\lib\site-packages\libratom\cli\subcommands.py", line 17, in <module>
    from libratom.cli.utils import MockContext, install_spacy_model, list_spacy_models
  File "c:\programdata\anaconda3\lib\site-packages\libratom\cli\utils.py", line 15, in <module>
    import spacy
  File "c:\programdata\anaconda3\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "c:\programdata\anaconda3\lib\site-packages\thinc\__init__.py", line 5, in <module>
    import numpy  # noqa: F401
  File "c:\programdata\anaconda3\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "c:\programdata\anaconda3\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('c:\\programdata\\anaconda3\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
---------------------

**Comment by judej** [comment]
@Biedubbeljoe, thanks for the report. An Insider Preview Windows build with the fix is now available. Build 20270 is now in the Dev Channel: blogs.windows.com/windows-insider/2020/12/03/announcing-windows-10-insider-preview-build-20270. If you are affected by this issue and want to test against the fix that will come via Windows Update, you can use this build. This is an insider build with other changes included, of course, so it is not entirely representative of the version that will be serviced, but it can be used to test for specific cases where the bug used to reproduce.
